spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres/contas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  url: jdbc:postgresql://localhost:5432/postgres/contas
  user: postgres
  password: postgres
  schemas: public
  locations: classpath:db/migration
  volumes:
    postgres_data:
