# docker build -t my-postgres .
# docker run -d -p 5432:5432 --name my-postgres-container my-postgres

FROM postgres:latest

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=contas

EXPOSE 5432